[vicon]
output_frequency=200
no_data_timeout_sec=10.0

[object_1]
input_object=Car@192.168.10.1
output_object=Car@192.168.11.2

[object_2]
input_object=OriginsX@192.168.10.1
output_object=OriginsX@192.168.11.2

# Add more objects as needed, e.g.:
# [object_2]
# input_object=Robot@192.168.10.2
# output_object=RobotOut@192.168.1.21

[noise]
enable_pos_noise=false
pos_noise_stddev=0.01
enable_att_noise=false
att_noise_stddev=0.01

[latency]
enable_latency=false
latency_ms=10.0

[rotation]
enable_rotation=false
rotation_preference=quaternion
quat_offset=0.0,0.0,0.0,1.0
rot_matrix_offset=1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
